// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAygF73e5iGq1QT3Fgd315Gy2Yri7hgps',
    appId: '1:513631515721:web:8794f1d1fc7126c1fabb98',
    messagingSenderId: '513631515721',
    projectId: 'winmax-pakistan',
    authDomain: 'winmax-pakistan.firebaseapp.com',
    storageBucket: 'winmax-pakistan.firebasestorage.app',
    measurementId: 'G-1VX7WHCSJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwaNWZ_a-lPF-CSWaBM_gu27kKu549eM',
    appId: '1:513631515721:android:89361b015aa95129fabb98',
    messagingSenderId: '513631515721',
    projectId: 'winmax-pakistan',
    storageBucket: 'winmax-pakistan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVXk45epQ6KBuHQWoFO6IuVFO08dbIzM',
    appId: '1:513631515721:ios:35b353d09301e3b1fabb98',
    messagingSenderId: '513631515721',
    projectId: 'winmax-pakistan',
    storageBucket: 'winmax-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.winmax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfVXk45epQ6KBuHQWoFO6IuVFO08dbIzM',
    appId: '1:513631515721:ios:35b353d09301e3b1fabb98',
    messagingSenderId: '513631515721',
    projectId: 'winmax-pakistan',
    storageBucket: 'winmax-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.winmax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAygF73e5iGq1QT3Fgd315Gy2Yri7hgps',
    appId: '1:513631515721:web:a45fbca1a04cd8e8fabb98',
    messagingSenderId: '513631515721',
    projectId: 'winmax-pakistan',
    authDomain: 'winmax-pakistan.firebaseapp.com',
    storageBucket: 'winmax-pakistan.firebasestorage.app',
    measurementId: 'G-XF0RFE0HNH',
  );
}
